# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/meal

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8


    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}


      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true

      - run:
          name: Test
          command: ./gradlew clean check build assembleAndroidTest

      - run:
          name: Run Linters
          command: ./gradlew check --stacktrace

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
