# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Run unit tests"
  lane :unitTest do
    gradle(task: "testDebugUnitTest --continue")
  end

  desc "Run Instrumented Tests"
  lane :automation_integrationTests do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/AVD_configs/AVD_config.json",
      gradle_task: "createDebugCoverageReport --continue"
    )
  end

  desc "Run Static Analyze"
  lane :staticAnalyze do
    gradle(task: "lintDebug")
  end

  desc "Build"
  lane :buildApp do
    gradle(task: "assembleDebug")
  end

  desc "Run Test And Coverage"
  lane :testAndCoverage do
    # automation_integrationTests
    gradle(task: "jacocoTestReport")
  end

  desc "Quality Gate"
  lane :qualityGate do
    gradle(task: "--info sonarqube")
  end


  desc "Pipeline"
  lane :pipeline do
    buildApp
    staticAnalyze
    testAndCoverage
  end

end
